### ISSUE TITLE
Throttle notifications failing to discord notifier

### ISSUE THREAD

**Issue by m1lkman** [l3uddz/cloudplow#101]
**Describe the bug**
When using discord notifications and throttling is enabled, throttle notifications fail. Other notifications are successful to discord, i.e. cloudplow start/stop. Tried both formats for url value 'https://' and 'discord://'.

**To Reproduce**
1. Configure both throttling and discord notification
2. Launch cloudplow
3. Errors are logged in cloudplow log and throttle notifications are not sent

**Logs**
```
2021-01-29 16:05:39,687 - ERROR      - apprise              - send                           - Error sending notification to 'https://discord.com/api/webhooks/xxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "/opt/cloudplow/utils/notifications/apprise.py", line 26, in send
    body=kwargs['message'],
  File "/usr/local/lib/python3.6/dist-packages/apprise/Apprise.py", line 434, in notify
    if not py3compat.asyncio.notify(coroutines, debug=self.debug):
  File "/usr/local/lib/python3.6/dist-packages/apprise/py3compat/asyncio.py", line 77, in notify
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'plex-monitor'.
```

**System Information**

 - Cloudplow Version: Master (latest)
 - Operating System: Ubuntu Server 18.04.5 LTS

**Comment by 8a8al00ey** [comment]
Try latest version

**Comment by saltydk** [comment]
should be fixed

**Comment by m1lkman** [comment]
works, thanks all
