### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by JuezFenix** [l3uddz/cloudplow#102]
**Describe the bug**
Error on trying to upload

**To Reproduce**
1. Remove excludes lines from  "uploader" section
2. Remote folder have spaces on their name

**Expected behavior**
Upload content from specified on config.json folder

**Logs**

`Traceback (most recent call last):
  File "/opt/cloudplow/utils/rclone.py", line 156, in upload
    excludes = self.__excludes2string()
  File "/opt/cloudplow/utils/rclone.py", line 187, in __excludes2string
    self.config['rclone_excludes']).replace('=None', '').strip()
KeyError: 'rclone_excludes'
2021-02-04 00:47:39,448 - ERROR      - cloudplow            - do_upload                      - Exception occurred while uploading: 
Traceback (most recent call last):
  File "/opt/cloudplow/cloudplow.py", line 377, in do_upload
    resp_delay, resp_trigger = uploader.upload()
  File "/opt/cloudplow/utils/uploader.py", line 53, in upload
    upload_status, return_code = rclone.upload(self.__logic)`

**System Information**

 - Cloudplow Version: Develop (latest)
 - Operating System: alpine (Docker)

**Additional context**

https://hub.docker.com/r/sabrsorensen/alpine-cloudplow/dockerfile

**Comment by saltydk** [comment]
You're missing rclone_excludes in your config.
