### ISSUE TITLE
Exception is thrown during service account rotation 

### ISSUE THREAD

**Issue by danialmoghaddam** [l3uddz/cloudplow#68]
**Describe the bug**
Checking for next available service account is failing. An sqlite exception is thrown and cloudplow will fail to switch to next available (unbanned) account.

**Logs**
2019-10-12 06:09:22,680 - ERROR      - cloudplow            - check_suspended_sa             - Exception checking suspended service accounts: 
Traceback (most recent call last):
  File "/opt/cloudplow/cloudplow.py", line 149, in check_suspended_sa
    if sa_delay[uploader_to_check] is not None:
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 243, in __getitem__
    item = self.conn.select_one(GET_ITEM, (key,))
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 515, in select_one
    return next(iter(self.select(req, arg)))
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 507, in select
    self.check_raise_error()
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 475, in check_raise_error
    reraise(e_type, e_value, e_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 71, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlitedict.py", line 409, in run
    cursor.execute(req, arg)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

**System Information**

 - Cloudplow Version: Master (latest)
 - Operating System: Ubuntu Server 16.04 LTS

**Comment by desimaniac** [comment]
Can you...

- Run it with debug?
  
   Change service file command argument: `--loglevel=INFO` to `--loglevel=DEBUG`
 
   paste the logs here:

- Check out and try and older commit. Ex 32d83dc82fb899b7804f0225d15b0dae72365149

**Comment by danialmoghaddam** [comment]
Restarted the service and all went back to normal.
